config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'
  devise_for :users
	root to: "articles#index"


	devise_scope :user do  
   	get '/users/sign_out' => 'devise/sessions#destroy'     
	end
  
  # post '/articles/approve/:id' => 'articles#approve_article'
  # post '/articles/approve' => 'articles#approve_article'


	resources :categories
	resources :articles do 
    member do
  		put 'approve' => 'articles#approve_article'
      put 'publish' => 'articles#publish'
    end
    collection do 
      get 'ajax_search' => 'articles#ajax_search'
    	get 'to_publish' => 'articles#publishable'
      put 'bulk_approve_article' => 'articles#bulk_approve_article'
      put 'bulk_publish_article' => 'articles#bulk_publish_article'
      match 'export_csv' => 'articles#export', :as => 'export_csv', :via => [:get, :post]
    end
	end
end

app/models/article.rb
require 'carrierwave/orm/activerecord'
include ArticleConcern

class Article < ApplicationRecord
	validates_presence_of :category_id, :title, :content
	belongs_to :category
	belongs_to :user
  
	#Followed this docs - https://code.tutsplus.com/uploading-with-rails-and-carrierwave--cms-28409a
	mount_uploader :image_url, AvatarUploader

	before_validation :assign_user_id, on: :create
	before_save :before_save_callback  # 1st
	after_save :after_save_callback  #4th
  before_create :before_create_callback # 2nd
  after_create :after_create_callback  #3rd

  before_commit :before_commit_callback #5th
  after_commit :after_commit_callback #6th

	self.per_page = 20

	private    #access specifiers public, private and protected

	def assign_user_id            # calling private method in console object.send(:method_name, var1,var2.....)
		self.user_id = User.current_user.id
		puts("user assigned")
	end

  def is_approved?
  	self.approved_by.present? 
  end










	def print_something(x, z="shivu")
		# binding.pry
		puts(z)
		puts(x)
	end

	def before_save_callback
		puts "before save callback"
	end

	def after_save_callback
		puts "after save callback"
	end

	def before_create_callback
		puts "before create callback"
	end

	def after_create_callback
		puts "after create callback"
	end

	def after_commit_callback
		puts "after commit callback" 
	end

	def before_commit_callback
		puts "before commit callback"
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:show, :edit, :update, :destroy, :approve_article, :publish]
  before_action :set_current_user
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, :only => [:approve_article, :publish, :bulk_approve_article, :bulk_publish_article, :ajax_search, :export]
  include ArticlesConcern

  def index
    search_article
  end

  def ajax_search  
    search_article
    response = render_to_string(template: "articles/ajax_search.json.jbuilder")
    render json: response
  end

  def new   # empty dummy object for new.html.erb
  	@article = Article.new()
  end

  def create
  	@article = Article.new(article_params)
  	# @article.user_id = current_user.id   => moved to model call back 
  	if @article.save!
      ArticleMailer.with(:title => @article.title).article_creation.deliver_now
  		redirect_to articles_path
  	else
  		render action: :new
  	end
  end

  def show
    @article = current_user.articles.find(params[:id])
  end

  def edit
  end

  def update
  	if @article.update(article_params)
  		redirect_to article_path(@article)
  	else
  		redirect_to articles_path, flash: "Can't update" 
  	end
  end

  def destroy
  	if @article.destroy 
  		redirect_to articles_path, notice: "Deleted successfully"
  	else
  		redirect_to articles_path, flash: "Can't delete"
  	end
  end

  def approve_article
    is_approved = false
    if @article.present? && current_user.is_admin && !@article.approved_by.present?
      @article.approved_by = current_user.id
      # @article.published_at = DateTime.now   #TODO: publish article
      @article.save
      # @articles = current_user.articles.where("approved_by != ? && published_at != ?", nil, nil).paginate(:page => params[:page]).order('id DESC') 

      is_approved = true
      message = "Article #{@article.title}: is approved successfully!!!"
    else
      message = "Article #{params[:id]}: not found or unable to approve"
    end
    # flash[:notice] = message
    respond_to do |format|  
      format.json { render json: {message: message}}
      format.html do 
        key = is_approved ? "notice" : "alert"
        flash[key] = message
        redirect_to articles_path
      end
    end
  end

  def bulk_approve_article
    is_all_approved = false
    approve_articles = params["article_ids"]
    if current_user.is_admin
      articles = Article.where(id: params["article_ids"])
      articles.update_all(approved_by: current_user.id)
      is_all_approved = true
      message = "All selected articles got approved !!!!!...."
    else
      message = "OOPs!... sorry, You are not authorized to approve any articles..."
    end 

    key = is_all_approved ? "notice" : "alert"
    flash[key] = message
    respond_to do |format|
      format.json { render json: {message: message}}
      format.html do
        redirect_to articles_path
      end
    end
  rescue StandardError => e 
    message = "OOps!... something went wrong, please try again"
    render json: {message: message}, status: 401
  end

  def publish
    is_published = false
    begin
      if @article.send(:is_approved?)
        @article.published_at = DateTime.now
        @article.save
        is_published = true
        message = "Published successfully......."
      end
    rescue Exception => e
      message = "unable to publish...... contact admin"
      puts "#{e.message}"
    end
    
    respond_to do |format| 
      format.json { render json: {message: message, article: @article} }
      format.html do 
        key = is_published ? "notice" : "alert"
        flash[key] = message 
        redirect_to articles_path
      end
    end
  end

  def bulk_publish_article
    is_all_published = false
    articles = Article.where(id: params["publish_ids"])
    articles.update_all(published_at: DateTime.now)
    is_all_published = true
    message = "Successfully published all selected articles!!!"
    key = is_all_published ? "notice" : "alert"
    flash[key] = message 
    respond_to do |format|
      format.json {render json:{message: message}}
      format.html do 
        redirect_to to_publish_path
      end
    end
  rescue StandardError => e 
    message = "OOps! something went wrong , please try again."
    render json: {message: message}, status: 401
  end

  def publishable
    @article = Article.new
    category_id = params["category"]["category_id"] rescue nil
    search = params[:search]
    if search.present?
      @articles = current_user.articles.includes(:user, :category).where("approved_by IS NOT NULL  && published_at IS NULL && title LIKE ?", "%#{search}%")
    elsif category_id.present?
      @articles = current_user.articles.includes(:user, :category).where("approved_by IS NOT NULL  && published_at IS NULL && category_id = ?", category_id)
    else 
      @articles = current_user.articles.includes(:user, :category).where("approved_by IS NOT NULL  && published_at IS NULL")
    end
    @articles = @articles.paginate(:page => params[:page]).order("id DESC")

    respond_to do |format|
      format.json {render json: {articles: @articles}}
      format.html do
        
      end
    end
  end

  def export
    respond_to do |format|
      format.json do
        begin
          category_id = params["article"]["category_id"]
          articles = current_user.articles.count
          if articles > 0
            Article.export_articles(category_id)
            message = "Exported initiated successfully"
          else
            puts " No article found"
            message = "No article found...."
          end
        rescue Exception => e
          message = e.message
        end    
        render json: {message: message}
      end
      format.js 
    end
  end

  private

  def article_params
  	params.require(:article).permit(:title, :content, :user_id, :category_id, :image_url) #, {image_url: []})
  end

  def find_article
    id = params[:id].present? ? params[:id] : params[:article_id]
	  @article = Article.find id
	end

	def set_current_user
		User.current_user = current_user
	end


end
 

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_export_articles.html.erb
<%= form_tag url_for(action: :export), method: :post, id: "export_articles" do %>
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
			<div class="form-group">
				<%= collection_select(:category, :category_id, Category.all, :id, :title, {:prompt => 'Select Category'}, class: "form-control input-sm", id: "export_by_category" )%>
			</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
			<div class="form-group">
				<%= submit_tag "Export", id: 'submit_export', class: "btn btn-success"%>
				<!-- <button onclick="exportArticles()" class="btn btn-info">Export</button> -->
			</div>
		</div>
	</div>
<% end %>

<script type="text/javascript">
	$('#export_articles').on("submit", function(e){
		e.preventDefault();
		const formData = new FormData(e.target);
		const formProps = Object.fromEntries(formData);
		var category_id = formProps["category[category_id]"];
		exportArticles(category_id);
	})

	function exportArticles(category_id){
		var xhr = new XMLHttpRequest;
		var input = {category_id};
		var body = JSON.stringify(input);
		var url = "http://localhost:3000/articles/export_csv"
		xhr.open('post', url, true);
		xhr.setRequestHeader('Content-Type', 'application/json');
		xhr.onreadystatechange =  function() {
			if(xhr.readyState == 4 && xhr.status == 200){
				var response = JSON.parse(xhr.responseText)
				alert(response["message"]);
			}
		}
		xhr.send(body);
	}

	$('#export_by_category').on('change', function(e) {
		$('#submit_export').removeAttr('disabled');
	});

app/views/articles/edit.html.erb
<%= render :partial => 'form', :locals => {:button_action => "Update Article"}%>

app/views/articles/export.js.erb
$('#render_export_articles').html("<%= escape_javascript render(partial: 'export_articles')%>");

app/views/articles/index.html.erb
<!--  approve single article using ajax 


<table border = "3">
	<thead>
	  <tr>
		<th>Sl.No</th>
		<th>Title</th>
		<th>Created By </th>
		<th>Category</th>
		<th colspan="3">Actions</th>
	  </tr>
	</thead>
	<div id = "approveable_articles">
		
	</div>
	<tbody>
		<%# @articles.each_with_index do |article, index| %>
			<tr id=<%#= "article_#{article.id}" %>>
				<td><%#= index +1 %></td>
				<td><%#= link_to article.title, article_path(article) %></td>
				<td><%#= article.user.name %></td>
				<td><%#= article.category.title %></td>
				<%# if current_user.is_admin %>
					<td><button onclick="approveArticle('<%#=article.id%>')">Approve</button></td>   
				<%# end %>
				<%# if current_user.id == article.user_id %>
					<td><%#= button_to "Destroy", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
				    <td><%#= link_to "Edit", edit_article_path(article)%></td>
				<%# end %>
		  </tr>
		<%# end %>
	</tbody>
</table>

<script type="text/javascript">
	function approveArticle(id) {
		var xhr = new XMLHttpRequest();
		// var url = `http://localhost:3000/articles/approve/${id}`
		var input = {id};
		var body = JSON.stringify(input)
		var url = `http://localhost:3000/articles/${id}/approve`
		xhr.open('PUT', url, true);
		xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function() {
        	if(xhr.readyState == 4 && xhr.status == 200) {
        		var response = JSON.parse(xhr.responseText);
        		var approveable_articles = document.getElementById('approveable_articles');
        		approveable_articles.innerHTML = response.message;  //innerHtML is a HTML element property. 
        		document.getElementById(`article_${id}`).remove();   // "#{}"==> ruby string interpolation `${}`==> js string interpolation
        	}
        }
        console.log(body);
        console.log(input);
		xhr.send(body);
	}
	
</script>
 -->

<div id = 'approveable_articles'>
</div>
<div class="row">
	<div class="col-md-2">
		<%= link_to "Add Article", new_article_path, class: 'btn btn-primary' %>
	</div>
	<div id  = "approve_button" class="col-md-3">
		<% if current_user.is_admin %>
			<button onclick="approveArticle()" class="btn btn-primary">Approve</button>
		<% end %>
	</div>
	<div class="d-flex flex-row-reverse col-md-5">
		<%= form_tag url_for(action: "index"), method: "get", id: "search_article", class: "form-inline" do  %>
			<%= text_field_tag "search", nil, placeholder: "Search by title", class: "form-control mb-3 mr-sm-3" %> 	
			<%= submit_tag "Search", class: "btn btn-success mb-3" %> 
		<% end %> 
	</div>   
</div>
<div class="d-flex justify-content-end">
	<div id = "article_count">
		<b>Total Number of Articles:</b> <%= @articles.length %>
	</div>
</div>
	

<table class="table table-stripped">
	<thead class="thead-dark">
		<tr>
		<th>SL No.</th>
		<th>Title </th> 
		<th>Created By </th>
		<th>Category </th>
		<% if current_user.is_admin %>
			<th>Approve </th>
		<% end %> 
		<th colspan="2"> Actions </th>
	</tr>

	</thead>
	<tbody id = "article_list">
		<%if @articles.present? %>
			<% @articles.each_with_index do |article, index| %>
				<tr id = <%= "article_#{article.id}" %>>
					<td> <%= index + 1 %> </td> 
					<td> <%= link_to article.title, article_path(article.id) %> </td>
					<td> <%= article.user.name %></td>
					<td> <%= article.category.title %> </td>
	                <% if current_user.is_admin %>
	                	<td> <input type='checkbox' class='articles' value= <%= article.id %> /> </td>
	                <% end %>
	                <% if current_user.id == article.user.id %>
	                	<td><%= button_to "Destroy", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %>
	                	</td>
					    <td><%#= link_to "Edit", edit_article_path(article)%>
					    	<a href= <%= "/articles/#{article.id}/edit" %> >Edit</a>
					    </td>
					<% else %>
						<td><%= button_to "Destroy", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, disabled: true %>
						</td>
					    <td><%#= link_to "Edit", edit_article_path(article), disabled: true%>
					    	<a href= <%= "/articles/#{article.id}/edit" %> style="pointer-events: none">Edit</a>
					    </td>
	                <% end %>
	                
				</tr>
			<% end %>
		<% else %> 
      <tr>
				<td colspan="6" style="text-align: center;"> <b> No data found!!!! </b> </td>
			</tr>
		<% end %>
	</tbody>
</table>

<style>
	table {
    border-collapse: separate;
    text-indent: initial;
    border-spacing: 2px;
    width: 100%;
}

	#article_count {
		margin: 10px;
	}
</style>

<script type="text/javascript">
	function approveArticle(e) {
		let allArticles = document.querySelectorAll('.articles')
		let selectedArticles = []
		allArticles.forEach(article => {
			if(article.checked){
				selectedArticles.push(article.value)
			}
		})
		console.log("article", selectedArticles)

	    articleBulkApprove(selectedArticles);
	}

	function articleBulkApprove(article_ids){
		var xhr = new XMLHttpRequest;
		var input = {article_ids};
    var body = JSON.stringify(input);
    var url = "http://localhost:3000/articles/bulk_approve_article"
    xhr.open('PUT', url, true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.onreadystatechange = function(){
    	if(xhr.readyState == 4 && xhr.status == 200) {
    		var response = JSON.parse(xhr.responseText);
    		var approveable_articles = document.getElementById('approveable_articles');
            // article_ids.forEach(article_id => {
            //   document.getElementById(`article_${article_id}`).remove();
            // })
            location.reload();
    		// approveable_articles.innerHTML = response.message
    	}
    }
    xhr.send(body);
	}

	var searchHandle = document.getElementById('search');
	
	searchHandle.addEventListener('keyup', function(){
		searchArticles();
	});

	searchHandle.addEventListener('keydown', function(){
		searchArticles();
	});

	function searchArticles(){
		var search = searchHandle.value;
		console.log(search);
		var articleCountHandle = document.getElementById('article_count');
		var articleListHandle = document.getElementById('article_list');
		if(search.length > 0){
			var xhr = new XMLHttpRequest;
			var input = {search};
			var body = JSON.stringify(input);
			var url = `http://localhost:3000/articles/ajax_search?search=${search}`
			xhr.open('GET', url, true);
			xhr.setRequestHeader('Content-Type', 'application/json');
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					var response = JSON.parse(xhr.responseText);
					articleCountHandle.innerHTML = `Total Number of Articles:- ${response["articles"].length}`;
          /*
          var articleList = [];
					response["articles"].forEach((article, i) => {
						console.log(article);
						articleList.push(`<tr><td> ${i + 1}</td><td> ${article["title"]}</td><td> ${article["user_name"]} </td><td>${article["category_title"]}</td></tr>`)
					})
					*/
					
					var articleList = response["articles"].map((article, i) => {
						return `<tr><td> ${i + 1}</td><td> ${article["title"]}</td><td> ${article["user_name"]} </td><td>${article["category_title"]}</td><td><form class="button_to" method="post" action="/articles/${article["id"]}"><input type="hidden" name="_method" value="delete" autocomplete="off"><input data-confirm="Are you sure?" type="submit" value="Destroy"><input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>" autocomplete="off"></form></td><td><a href="/articles/${article["id"]}/edit">Edit</a></td></tr>`
					})
					articleListHandle.innerHTML = articleList.join('\n');
				}
			}
			xhr.send(body);
		}
	}
</script>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<%= render :partial => 'form', :locals => {:button_action => "Create Article"}%>

app/views/articles/publishable.html.erb
<!-- <table border = "3">
	<thead>
	  <tr>
		<th>Sl.No</th>
		<th>Title</th>
		<th>Created By </th>
		<th>Category</th>
		<th colspan="1">Actions</th>
	  </tr>
	</thead>
	<div id = "publishable_articles">
		
	</div>
	<tbody>
		<%# if @articles.present? %>
			<%# @articles.each_with_index do |article, index| %>
				<tr id=<%#= "article_#{article.id}" %>>
					<td><%#= index +1 %></td>
					<td><%#= link_to article.title, article_path(article) %></td>
					<td><%#= article.user.name %></td>
					<td><%#= article.category.title %></td>
					<%# if current_user.id == article.user_id %>
					    <td><%#= link_to "Edit", edit_category_path(article)%></td>
						<td><button onclick="publishArticle('<%#=article.id%>')">Publish</button></td>
					<%# end %>
			  </tr>
			<%# end %>
		<%# else %>
			<tr>
				<td colspan="5"><b> No articles got approved to get publish...... </b></td>
			</tr>
		<%# end %>
	</tbody>
</table>

<script type="text/javascript">
	function publishArticle(id) {
		var xhr = new XMLHttpRequest();
		var input = {id};
		var body = JSON.stringify(input)
		var url = `http://localhost:3000/articles/${id}/publish`
		xhr.open('PUT', url, true);
		xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function() {
        	if(xhr.readyState == 4 && xhr.status == 200) {
        		var response = JSON.parse(xhr.responseText);
        		var publishable_articles = document.getElementById('publishable_articles');
        		publishable_articles.innerHTML = response.message;
        		document.getElementById(`article_${id}`).remove();
        	}
        }
		xhr.send(body);
	}
	
</script> -->
<div class="row">
	<div class="col-md-5">
		<%= form_tag url_for(action: :publishable), method: :get, id: "filter_by_category" do %>
			<div class = "row">
				<div class = "col-md-10" id = "form_category_category_id">
					<div class="form-group">
						<%= collection_select(:category, :category_id, Category.all, :id, :title, {:prompt => 'Select Category'}, class: "form-control")%>
					</div>
				</div>
				<div class = "col-sm-2">
					<div class="form-group">
						<%= submit_tag "Filter", class: "btn btn-primary" %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-md-4">
		<%= form_tag url_for(action: :publishable), method: :get, id: "search_publishable_articles" do %>
			<div class = "row">
				<div class = "col-sm-8">
					<div class="form-group">
						<span id = "search_error"></span>
						<%= text_field_tag "search", nil, placeholder: "Search by title", class: "form-control"%> &nbsp;				
					</div>
				</div>
				<div class="col-sm-2" id = "search_button">
					<div class="form-group">
						<%= submit_tag "search", class: "btn btn-primary" %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<div>

<div class = "row">
	<div class="col-md-3" id = "publish_button" >
		<button onclick="publishArticle()" class="btn btn-success">Publish</button>
	</div>
	<div class = "col-md-8" id= "render_export_articles">
		<%= link_to "Export", export_csv_articles_path, remote: true, class: "btn btn-info"%>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 article_table">
		<table class = "table table-bordered">
			<thead class="thead-dark">
				<tr>
					<th> # </th>
					<th> Sl.No </th>
					<th> Title </th>
					<th> Created By </th>
					<th> Category </th> 
					<!-- <th> Action </th> -->
				<tr>
			</thead>
			<tbody id = "publishable_articles">
				<% if @articles.present? %>
					<% @articles.each_with_index do |article, index| %>
						<tr>
							<td> <input type="checkbox" class="publish" value= <%= article.id %> /></td>
							<td> <%= index + 1 %> </td>
							<td> <%= article.title %> </td>
							<td> <%= article.user.name %> </td>
					     	<td> <%= article.category.title %> </td>	
						</tr>
					<% end %>	
				<% else %>
					<tr>
						<td colspan="5" style="text-align: center;"> <b>No Articles found.!!!</b> </td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<style>
	table {
    border-collapse: separate;
    text-indent: initial;
    border-spacing: 2px;
    min-width: 100%;
	}

	.article_table{
		width: 100%;
	}

	#form_category_category_id{
		padding: 0px;
		margin: 0px;

	}

	#search_button{
		padding: 0px;
		margin: 0px;

	}
</style>

<script type="text/javascript">
	function publishArticle(e){
    let publishArticles = document.querySelectorAll('.publish');
    var checkedArticles = [];
    publishArticles.forEach(article => {
    	if(article.checked){
    		checkedArticles.push(article.value);
    	}
    })
    articleBulkPublish(checkedArticles);
	}

	function articleBulkPublish(publish_ids){
		console.log(publish_ids);
		var xhr = new XMLHttpRequest;
		var input = {publish_ids};
		var body = JSON.stringify(input);
		var url = "http://localhost:3000/articles/bulk_publish_article"
		xhr.open('PUT', url, true);
		xhr.setRequestHeader('Content-Type', 'application/json')
		xhr.onreadystatechange = function() {
			if(xhr.readyState == 4 && xhr.status == 200) {
				// var response = JSON.parse(xhr.responseText);
				// var publishable_articles = document.getElementById('publishable_articles');
				location.reload()
			}
		}

		xhr.send(body);

	}

	var searchableArticlesHandle = document.getElementById('search_publishable_articles');
	searchableArticlesHandle.addEventListener("submit", function(e){
		e.preventDefault();

		const formData = new FormData(e.target);
		const formProps = Object.fromEntries(formData);
		const searchValue = formProps["search"];
		var publishableArticlesHandle = document.getElementById('publishable_articles');
		if(searchValue != ""){
			var xhr = new XMLHttpRequest;
			var url = `http://localhost:3000/articles/to_publish?search=${searchValue}`
			xhr.open('get', url, true);
			xhr.setRequestHeader('Content-Type', 'application/json');
			xhr.onreadystatechange =  function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					var response = JSON.parse(xhr.responseText);
					var articles = response["articles"];
					buildArticlesHtml(articles, publishableArticlesHandle);
				}
			}
			xhr.send();
		}
		else {
			var searchErrorHandle = document.getElementById('search_error');
			searchErrorHandle.innerHTML = "Please enter the search text";
			searchErrorHandle.setAttribute("style", "color: red;");
		}	
	})


	function buildArticlesHtml(articles, handle){
		handle.innerHTML = "";
		articles.forEach((article, i) => {
     	var tr = document.createElement('tr');

     	var td1 = document.createElement('td');
     	var input = document.createElement('input');
     	var type = document.createAttribute('type');
     	var klass = document.createAttribute('class');
     	var value = document.createAttribute('value');
     	type.value = "checkbox";
     	klass.value = "publish";
     	value.value = article.id;

     	input.setAttributeNode(type);
     	input.setAttributeNode(klass);
     	input.setAttributeNode(value);
    
     	td1.appendChild(input);
     	tr.appendChild(td1);

     	var td2 = document.createElement('td');
     	var text2 = document.createTextNode(i + 1);
     	td2.appendChild(text2);
     	tr.appendChild(td2);

     	var td3 = document.createElement('td');
     	var text3 = document.createTextNode(article.title);
     	td3.appendChild(text3);
     	tr.appendChild(td3);

     	var td4 = document.createElement('td');
     	var text4 = document.createTextNode("username");
     	td4.appendChild(text4);
     	tr.appendChild(td4);

     	var td5 = document.createElement('td');
     	var text5 = document.createTextNode("category");
     	td5.appendChild(text5);
     	tr.appendChild(td5);
      
      
      handle.appendChild(tr);
		})
	}
</script>

<%= will_paginate @articles %>

app/views/articles/show.html.erb
<b>Title : </b> <%= @article.title %><br/>
	<% if @article.image_url.present? %>
		<%= image_tag  @article.image_url.url, size: "160x100", alt: "No image" %>
	<% end %>
<b>Content : </b> <%= @article.content %><br/>
<b>Created_by : </b> <%= @article.user.name %><br/>
<b>Category : </b> <%= @article.category.title %><br/>