config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'
  devise_for :users
	root to: "articles#index"


	devise_scope :user do  
   	get '/users/sign_out' => 'devise/sessions#destroy'     
	end
  
  # post '/articles/approve/:id' => 'articles#approve_article'
  # post '/articles/approve' => 'articles#approve_article'


	resources :categories
	resources :articles do 
    member do
  		put 'approve' => 'articles#approve_article'
      put 'publish' => 'articles#publish'
    end
    collection do 
      get 'ajax_search' => 'articles#ajax_search'
    	get 'to_publish' => 'articles#publishable'
      put 'bulk_approve_article' => 'articles#bulk_approve_article'
      put 'bulk_publish_article' => 'articles#bulk_publish_article'
      match 'export_csv' => 'articles#export', :as => 'export_csv', :via => [:get, :post]
    end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :title, :description
	validates_uniqueness_of :title
  
  has_many :articles
	self.per_page = 20
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

  def index
  	# @categories = Category.all
    if params[:search].present?
      # @categories = Category.where("title LIKE ?", "%" + params[:search] + "%").paginate(:page => params[:page]).order('id DESC')
      @categories = Category.includes(:articles).where("title LIKE ?", params[:search] + "%").paginate(:page => params[:page]).order('id DESC')
    else
      @categories = Category.includes(:articles).paginate(:page => params[:page]).order('id DESC')
    end

    respond_to do |format|
      format.json {render json: {categories: @categories}}
      format.html
    end
  end

  def new
		@category = Category.new  	
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to categories_path, notice: "Created successfully"
  	else
  		render action: 'new'
  	end
  end

  def show
  	# @articles = Article.where(category_id: @category.id)    
    # @category = @category.includes(:articles)
    if params[:search].present?
      # @categories = Category.where("title LIKE ?", "%" + params[:search] + "%").paginate(:page => params[:page]).order('id DESC')
      @articles = @category.articles.where("user_id = ?", current_user.id).where("title LIKE ?", params[:search] + "%").paginate(:page => params[:page]).order('id DESC')
    else
       @articles = @category.articles.where("user_id = ?", current_user.id).paginate(:page => params[:page]).order('id DESC')
    end
  end

  def destroy
  	if @category.destroy
  		redirect_to categories_path, notice: "Category deleted"
  	else
  		redirect_to categories_path, flash: "Can't delete the record"
  	end
  end

  def edit
  	
  end

  def update
  	if @category.update(category_params)
  	  redirect_to category_path(@category), notice: "Category Updated"
  	else
  		redirect_to categories_path, flash: "Can't find record" 
  	end 
  end

  private

  def category_params
  	params.require(:category).permit(:title, :description)
  end

  def find_category
  	@category = Category.find params[:id]
 	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div>
	<%= form_for @category do |f| %>
	 <% if @category.errors.present? %>
	  <h2> <%= pluralize(@category.errors.count, 'error')%> prohibited creation of category </h2> 
	 <% end %>
     <ul>
	   <% @category.errors.full_messages.each do |e| %>
	   	<li><%= e %></li>
	   <% end %>
	  </ul>
	   <br/><br/>
	   <b><%= f.label :Title %>:</b> <%= f.text_field :title %><br/><br/>
	   <b><%= f.label :Description %>:</b> <%= f.text_area :description %><br/><br/>
	    <%= f.submit :save %>
	<% end %>
</div>

app/views/categories/edit.html.erb
<%= render :partial => 'form'%>

app/views/categories/index.html.erb
<%= link_to "Add category", new_category_path %>
<br/>
<h1> List of categories - <%= @categories.length %> </h1> 
<%= form_tag '/categories', method: :get do %>
	<%= label_tag :Search %>: 
	<%= text_field_tag :search %>
	<%= submit_tag :search %>
<% end %>
<br/>
<table border="3">
	<thead>
	<tr>
		<th> Sl.No </th>
		<th>Title</th>
		<th>Description</th>
		<th>No of Articles</th>
		<th colspan="2">Actions</th>
	</tr>
	</thead>
	<tbody>
		<% @categories.each_with_index do |category, index| %>
			<tr>
                <td><%= index+1 %></td>
				<td><%= link_to category.title, category_path(category) %></td>
				<td><%= category.description %></td>
				<td><%= category.articles.length %></td>
				<td><%= link_to "Edit", edit_category_path(category)%></td>
				<td><%= button_to "Destroy", category_path(category), method: :delete, data: { confirm: "Are you sure?" } %></td>
			</tr>
		<% end %>
	</tbody>
</table><br/>

<%= link_to "Back", :back %>

<%= will_paginate @categories %>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<h1> <%= @category.title %> </h1>
<p> <%= @category.description %> </p>

<h1> List of Articles </h1>

<% if @articles.present? %>
	<table border = "3">
		<thead>
		  <tr>
			<th>Sl.No</th>
			<th>Title</th>
			<th>Created By </th>
			<th>Category</th>
		  </tr>
		</thead>

		<tbody>
			<% @articles.each_with_index do |article, index| %>
				<tr>
					<td><%= index +1 %></td>
					<td><%= link_to article.title, article_path(article) %></td>
					<td><%= article.user.name %></td>
					<td><%= article.category.title %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<h2> No data to display  </h2>
<% end %>

<%= will_paginate @articles %>