config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'
  devise_for :users
	root to: "articles#index"


	devise_scope :user do  
   	get '/users/sign_out' => 'devise/sessions#destroy'     
	end
  
  # post '/articles/approve/:id' => 'articles#approve_article'
  # post '/articles/approve' => 'articles#approve_article'


	resources :categories
	resources :articles do 
    member do
  		put 'approve' => 'articles#approve_article'
      put 'publish' => 'articles#publish'
    end
    collection do 
      get 'ajax_search' => 'articles#ajax_search'
    	get 'to_publish' => 'articles#publishable'
      put 'bulk_approve_article' => 'articles#bulk_approve_article'
      put 'bulk_publish_article' => 'articles#bulk_publish_article'
      match 'export_csv' => 'articles#export', :as => 'export_csv', :via => [:get, :post]
    end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :patient
	belongs_to :physician
end

app/models/article.rb
require 'carrierwave/orm/activerecord'
include ArticleConcern

class Article < ApplicationRecord
	validates_presence_of :category_id, :title, :content
	belongs_to :category
	belongs_to :user
  
	#Followed this docs - https://code.tutsplus.com/uploading-with-rails-and-carrierwave--cms-28409a
	mount_uploader :image_url, AvatarUploader

	before_validation :assign_user_id, on: :create
	before_save :before_save_callback  # 1st
	after_save :after_save_callback  #4th
  before_create :before_create_callback # 2nd
  after_create :after_create_callback  #3rd

  before_commit :before_commit_callback #5th
  after_commit :after_commit_callback #6th

	self.per_page = 20

	private    #access specifiers public, private and protected

	def assign_user_id            # calling private method in console object.send(:method_name, var1,var2.....)
		self.user_id = User.current_user.id
		puts("user assigned")
	end

  def is_approved?
  	self.approved_by.present? 
  end










	def print_something(x, z="shivu")
		# binding.pry
		puts(z)
		puts(x)
	end

	def before_save_callback
		puts "before save callback"
	end

	def after_save_callback
		puts "after save callback"
	end

	def before_create_callback
		puts "before create callback"
	end

	def after_create_callback
		puts "after create callback"
	end

	def after_commit_callback
		puts "after commit callback" 
	end

	def before_commit_callback
		puts "before commit callback"
	end
end

app/models/assembly.rb
class Assembly < ApplicationRecord
	has_and_belongs_to_many :parts
end

app/models/cat.rb
class Cat < Pet
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :title, :description
	validates_uniqueness_of :title
  
  has_many :articles
	self.per_page = 20
end

app/models/dog.rb
class Dog < Pet
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_one :picture, as: :imageable
	has_many :subordinates, class_name: "Employee", foreign_key: "manager_id"
	belongs_to :manager, class_name: "Employee", optional: true
end

app/models/part.rb
class Part < ApplicationRecord
	has_and_belongs_to_many :assemblies
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :physicians, through: :appointments
end


=begin 
p = Physician.first
p.patients

select * from patients inner join appointments on patients.id = appointments.patients where appointments.physician_id = p.id;

Physician
1, 2, 3

Patient
1, 2, 3

appointments
patient_id 1, physician_id 1 
patient_id 2, physician_id 1

p = Patient.last
p.physicians
select ph.name as physician_name, p.name as patient_name from physicians ph inner join appointments ap on ph.id = ap.physician_id where ap.patient_id = p.id;

p.appointments.create(physician_id: 123)

habtm 

p.physicians.create(name: 'shiva')


date  = Time.now - 2.days
physician = 1

results = ActiveRecord::Base.connection.execute("select ap.id, p.name, ph.name, ap.appointment_date from appointments ap 
inner join patients p on p.id = ap.patient_id
inner join physicians ph on ph.id = ap.physician_id
where ap.appointment_date > '2024-02-02 15:40:18 +0530' and ap.physician_id = 10;")

results = ActiveRecord::Base.connection.execute("select ph.name as physician_name, p.name as patient_name from physicians ph inner join appointments ap on ph.id = ap.physician_id  inner join patients p on p.id = ap.patient_id where ap.patient_id = p.id;")

assembly habtm :parsts
part habtm :assemblies

assemblies_parts

database


Polymorphic associations

Employee -
	name, email, age, image

	has_many :images, as: :imageable

Product 
	name, price, image
	p = Product.first 
	p.image 

	has_many :images, as: :images

Picture
  imageable_id - employee.id
  imageable_type - Employee
  imageurl - 

	belongs_to :imageable, polymorphic: true


  imageable_id - product.id
  imageable_type - Product
  imageurl - 

	




=end

app/models/pet.rb
class Pet < ApplicationRecord

end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :pictures, as: :imageable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  class << self
    def current_user=(user)      #setter method or writer method
      Thread.current[:current_user] = user
    end
 
    def current_user             #getter method or reader method
      Thread.current[:current_user]
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :authenticate_user!
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :jquery, :jquery_ujs %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <%#= javascript_include_tag 'application' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <% link = current_user.is_admin ? "Articles To Be Approved" : "Published Articles" %>
                 <%= link_to link, articles_path, class: "nav-link" %> 
              </li>
              <li class="nav-item">
                <%= link_to "Categories", categories_path, class: "nav-link" %> 
              </li>
              <li class="nav-item">
                <%= link_to "Approved articles to publish",to_publish_articles_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %> 
              </li>
              <li class="nav-item nav-link" >
                <%= current_user.name %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>